version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017

clone_folder: c:\projects\croaring

platform:
- x64

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017" # x86 build
      AVXFLAG: "OFF"

build_script:
  - mkdir build
  - cd build
  - ps: cmake -G "$env:GENERATOR" -DFORCE_AVX="$env:AVXFLAG" ..
  - cmake --build .
  - dir
  - dir tests
  - dir tests\toplevel_unit.dir
  - dir tests\Debug
  - tests\Debug\toplevel_unit
  - ctest

artifacts:
  - path: build
